### ISSUE TITLE
Changing to 10log10, then back, sets wrong Y scale

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/sigplot#27]
**Describe the bug**
Going into and immediately back out of CMODE 10log10 with the mouse leads to incorrect scales.

**To Reproduce**
If I change CX mode to 10log10, then immediately back to real/magnitude (whatever it was originally), the scale is off. MM "Expand Full" on Y thumb leads to another wrong scale. LM zoom followed by unzoom restores the scale as expected.

I've seen this on a variety of files, although it's more obvious on some than others. 

**Expected behavior**
I think that changing back to the original display mode should reset the viewport to what it was originally.

**jsFiddle**
The fiddle https://jsfiddle.net/ha09baqu/ actually demonstrates it if you turn off `autohide_panbars`.

**Desktop (please complete the following information):**
 - CentOS Linux release 7.5.1804 (Core)
 - Chrome version 70.0.3538.77

**Additional context**
Not sure if this is related to #14

**Comment by maihde** [comment]
Thanks!  I modified the fiddle and was able to reproduce it without the mouse (since the mouse clicks simply call change_settings).

https://jsfiddle.net/kzhvwnfx/

I'll get a unittest implemented and then fix this.  Thanks for reporting it.

**Comment by maihde** [comment]
Just as a side-note, it's not that the scale is off, here is the plot prior to a cmode change:

![image](https://user-images.githubusercontent.com/229922/49198947-9f9d5400-f363-11e8-820f-7b859d161077.png)

The triangle correctly goes from 1 to 5 on the y-axis.  After changing to 10*log10 the plot is still rending correctly and the panbars have shrunk to allow panning to the new full range of data:

![image](https://user-images.githubusercontent.com/229922/49198991-ceb3c580-f363-11e8-8d3c-c4ab31e14315.png)

After changing back to the original cmode, the triangle is still correctly rendered from 1 to 5:

![image](https://user-images.githubusercontent.com/229922/49199027-ebe89400-f363-11e8-89b2-1fbf7d5ba654.png)

But the panbars still allow you to pan to a larger range.  Select "Expand Full" further confirms that the plot is rendering correctly, but the panrange is simply too large:

![image](https://user-images.githubusercontent.com/229922/49199064-0fabda00-f364-11e8-96b3-b4464dce53a8.png)

Because the triangle still correctly renders 1 to 5.

The zoom/unzoom action then triggers the pan range to be reset.

Anyways it's still a bug to fix, but I wanted to clarify what I was fixing.

**Comment by maihde** [comment]
Okay, I've made a fix.  The regression was introduced on this commit (e68cab3) because it incorrectly set `Gx.cmode` before calling `changemode()`.  This caused the `changemode` logic to think that no change to pan area was necessary.  A unittest has been added to prevent this in the future.

**Comment by sterre** [comment]
https://github.com/LGSInnovations/sigplot/commit/d72351631fffbaac4eafdd0726899538e191e52a fixes my original reproducer. Thanks!
